name: 'Deploy code to AWS S3'
description: 'Deploy project code to cloud aws s3 bucket'
inputs:
  bucket:
    description: 'This is S3 bucket name'
    required: true
  bucket-region:
    description: 'The region of S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder containing the deployable files'
    required: true
runs:
  using: 'node20'
  main: 'main.js'

