name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependency
        id: cache-deps-id
        uses: ./.github/actions/cached-dependancy
        with:
          caching: 'false'
      - name: Outputs cache used information
        run: echo "Cache used? ${{ steps.cache-deps-id.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependency
        uses: ./.github/actions/cached-dependancy
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependency
        uses: ./.github/actions/cached-dependancy
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        id: deploy-id
        uses: ./.github/actions/deploy-s3-javascript
        env:
          # AWS_ACCESS_KEY_ID: <my aws access key>
          # AWS_SECRET_ACCESS_KEY: <my aws sceret access key>
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: <my s3 bucket name> 
          bucket-region: <my s3 bucket region>
          dist-folder: ./dist
      - name: Display deployed website URL
        run: echo "Live Site URL- ${{ steps.deploy-id.outputs.websile-url }}"